credentials:
  usernames:
    master_user:
      email: master@example.com
      name: Master Account
      password: "$2b$12$6fvhz8Cy2zXwz.NCM5VX6Og4qjMY0NxxJzUgKcDsbE2tK4CIsgVbq"

cookie:
  expiry_days: 30
  key: "dga_app_cookie"
  name: "dga_app_auth"
